---
- name: Create envoy service and directories
  hosts: localhost
  connection: local 
  gather_facts: false
  become: no
  tasks:

    - name: Create subdirectories
      file: 
        path: /data/envoy 
        state: directory 

    - name: Generate envoy.service file
      become: yes
      copy: 
        src: ../../envoy/envoy.service
        dest: /etc/systemd/system/envoy.service
   
    - name: Reload envoy.service
      become: yes
      systemd: 
        daemon_reload: yes

    - name: Stop the daemon
      become: yes
      systemd: 
        name: envoy 
        enabled: yes 
        state: stopped

    - name: Move envoy_config.yaml to envoy/
      copy: 
        src: ../../envoy/envoy_config.yaml
        dest: /data/envoy/envoy_config.yaml

    - name: Start the envoy service
      become: yes
      systemd: 
        name: envoy
        enabled: yes
        state: restarted
