---
- name: Set up regular node.
  hosts: localhost
  connection: local 
  gather_facts: yes 
  vars:
    besu_version: '20.10.1'

  tasks:

# Creación de la estructura de directorios

    - name: Set BESU_P2P_HOST rule
      become: yes
      lineinfile:
        path: /etc/environment
        state: present
        line: BESU_P2P_HOST={{ ansible_default_ipv4.address }}

    - name: Create subdirectories
      file: 
        path: /data/{{item}} 
        state: directory 
      with_items:
      - besu
      - versionesBesu

    - name: Create subdirectories
      file: 
        path: /data/besu/{{item}} 
        state: directory
      with_items:
      - config
      - keys
      - config/besu
      - keys/besu

    - name: Pre-remove temp besu directory
      become: yes
      file:
        path: /tmp/besu
        state: absent

    - name: Create temp besu directory
      become: yes
      file:
        path: /tmp/besu
        state: directory

    - name: Pull besu binaries
      become: yes
      get_url:
        url: "https://dl.bintray.com/hyperledger-org/besu-repo/besu-{{besu_version}}.tar.gz"
        dest: "/tmp/besu/besu.tar.gz"

    - name: Extract besu binaries
      unarchive:
        src: "/tmp/besu/besu.tar.gz"
        dest: /data/versionesBesu/
        copy: no

# Configuración desde ficheros de configuración en github público

    - name: Generate besu unit file
      become: yes
      copy: 
        src: templates/besu.service
        dest: /etc/systemd/system/besu.service
   
    - name: Reload besu service
      become: yes
      systemd: daemon_reload=yes

    - name: Stop the daemon
      become: yes
      systemd: 
        name: besu.service
        enabled: yes 
        state: stopped

    - name: Symbolic link bin for new besu version
      file: 
        src: /data/versionesBesu/besu-{{besu_version}}/bin 
        dest: /data/besu/bin
        state: link

    - name: Symbolic link lib for new besu version
      file: 
        src: /data/versionesBesu/besu-{{besu_version}}/lib
        dest: /data/besu/lib
        state: link
    
    - name: Bring xml log strategy file into besu/config
      copy: 
        src: ../../config/log-config.xml
        dest: /data/besu/config/besu/

    - name: Bring genesis.json in place
      copy: 
        src: ../../config/genesis.json
        dest: /data/besu/config/besu/genesis.json

    - name: Bring regular config.toml in place
      copy: 
        src: ../../config/config.toml
        dest: /data/besu/config/besu/config.toml

    - name: Remove unnecessary folder transit
      become: yes
      file:
        path: /tmp/transit
        state: absent

    - name: Remove unnecessary folder besu
      become: yes
      file:
        path: /tmp/besu
        state: absent

    - name: Add +x to get_keys.sh
      file:
        path: ../../get_keys.sh
        mode: +x    

    - name: Exec get_keys.sh
      shell: .././get_keys.sh

    - name: Recursively change ownership of a directory
      become: yes
      file:
        path: /data/besu
        state: directory
        recurse: yes
        owner: besu
        group: besu

    - name: start the besu service
      become: yes
      systemd: 
        name: besu
        enabled: yes
        state: restarted
