---
- name: Create besu user
  hosts: localhost
  connection: local
  
  tasks:
    - name: Create a user 
      become: yes
      user:
        name: besu
        comment: Besu user
        shell: /sbin/nologin
        system: yes
        createhome: no
