---
- name: Create envoy service and directories
  hosts: localhost
  connection: local 
  gather_facts: false
  become: no
  tasks:

# Creaci贸n de la estructura de directorios

    - name: Create subdirectories
      file: 
        path: /data/envoy 
        state: directory 

# Configuraci贸n desde ficheros de configuraci贸n y creaci贸n del servicio envoy

    - name: Generate envoy unit file
      become: yes
      copy: 
        src: ../envoy/envoy.service
        dest: /etc/systemd/system/envoy.service
   
    - name: Reload envoy service
      become: yes
      systemd: 
        daemon_reload: yes

    - name: Stop the daemon
      become: yes
      systemd: 
        name: envoy 
        enabled: yes 
        state: stopped

    - name: Bring envoy.yaml into envoy directory
      copy: 
        src: ../envoy/envoy_config.yaml
        dest: /data/envoy/envoy_config.yaml

    - name: Generate envoy unit file
      become: yes
      copy:
        src: ../envoy/startEnvoy.sh
        dest: /data/envoy/startEnvoy.sh

    - name: Add +x to startEnvoy.sh
      become: yes
      file:
        path: /data/envoy/startEnvoy.sh
        mode: +x

    - name: Start the envoy service
      become: yes
      systemd: 
        name: envoy
        enabled: yes
        state: restarted
